export const EXPANDED_IMAGES = {
  articles: "/manus-storage/casinooverse-textfree-013_2e007f4d.jpg",
  history: "/manus-storage/casinooverse-textfree-037_aa3e003b.jpg",
  culture: "/manus-storage/casinooverse-textfree-038-v2_19733cfb.jpg",
  destinations: "/manus-storage/cv-casino-editorial-destinations_5218f6fb.jpg",
  facts: "/manus-storage/cv-casino-editorial-facts_992a1d46.jpg",
  gallery: "/manus-storage/casinooverse-textfree-041-v2_99d242e8.jpg",
  poker: "/manus-storage/cv-casino-editorial-poker_d038178d.jpg",
  blackjack: "/manus-storage/cv-casino-editorial-blackjack_309a005d.jpg",
  roulette: "/manus-storage/cv-casino-editorial-roulette_3fb03642.jpg",
  baccarat: "/manus-storage/cv-casino-editorial-baccarat_a49142ce.jpg",
  slots: "/manus-storage/cv-casino-editorial-slots_e4af86da.jpg",
  galleryArchitecture: "/manus-storage/cv-redesign-gallery-architecture-v3_d585d9ab.jpg",
  galleryInteriors: "/manus-storage/cv-redesign-gallery-interiors-v3_b8fa492f.jpg",
  galleryCards: "/manus-storage/cv-redesign-gallery-cards-v3_9e905a09.jpg",
  galleryRoulette: "/manus-storage/cv-redesign-gallery-roulette-v3_f7f76037.jpg",
  galleryEntertainment: "/manus-storage/cv-redesign-gallery-entertainment-v3_21e0c2e2.jpg",
  galleryDestination: "/manus-storage/cv-redesign-gallery-destination-v3_578403a6.jpg",
  galleryAccessibility: "/manus-storage/cv-redesign-gallery-accessibility-v3_468a3511.jpg",
  galleryArchive: "/manus-storage/casinooverse-textfree-049_9a38a7ee.jpg",
} as const;
