export const EXPANDED_IMAGES = {
  articles: "/manus-storage/cv-redesign-articles-v4_69591d07.jpg",
  history: "/manus-storage/cv-redesign-history-v4_cf82e89c.jpg",
  culture: "/manus-storage/cv-redesign-culture-v4_e1cb755e.jpg",
  destinations: "/manus-storage/cv-redesign-destinations-v4_d2e7da53.jpg",
  vlogs: "/manus-storage/cv-redesign-vlogs-v4_c125d3ce.jpg",
  facts: "/manus-storage/cv-redesign-facts-v3_414c76b9.jpg",
  gallery: "/manus-storage/cv-redesign-gallery-v3_952b0523.jpg",
  poker: "/manus-storage/cv-redesign-poker-v3_e0528832.jpg",
  blackjack: "/manus-storage/cv-redesign-blackjack-v3_437bd807.jpg",
  roulette: "/manus-storage/cv-redesign-roulette-v3_6038895d.jpg",
  baccarat: "/manus-storage/cv-redesign-baccarat-v3_2791ef7d.jpg",
  slots: "/manus-storage/cv-redesign-slots-v3_24716dd1.jpg",
  galleryArchitecture: "/manus-storage/cv-redesign-gallery-architecture-v3_d585d9ab.jpg",
  galleryInteriors: "/manus-storage/cv-redesign-gallery-interiors-v3_b8fa492f.jpg",
  galleryCards: "/manus-storage/cv-redesign-gallery-cards-v3_9e905a09.jpg",
  galleryRoulette: "/manus-storage/cv-redesign-gallery-roulette-v3_f7f76037.jpg",
  galleryEntertainment: "/manus-storage/cv-redesign-gallery-entertainment-v3_21e0c2e2.jpg",
  galleryDestination: "/manus-storage/cv-redesign-gallery-destination-v3_578403a6.jpg",
  galleryAccessibility: "/manus-storage/cv-redesign-gallery-accessibility-v3_468a3511.jpg",
  galleryArchive: "/manus-storage/cv-redesign-gallery-archive-v3_6f28d974.jpg",
} as const;
