import { Link } from "wouter";
import { ArrowRight, Building2, MapPinned, Scale, TrainFront } from "lucide-react";
import { Seo } from "@/components/Seo";
import { ResearchReferences } from "@/components/ResearchReferences";
import { SectionHeading } from "@/components/SectionHeading";
import { EXPANDED_IMAGES } from "@/lib/expandedContent";

const destinations = [
  { place: "Las Vegas", country: "United States", period: "Rail town · legalized gaming in 1931", text: "Las Vegas moved from a rail and desert-service economy toward a regulated visitor economy. Postwar roadside properties, neon competition, corporate investment, convention infrastructure, and large entertainment programs created several distinct architectural eras.", lens: "Read the city through transport, water, labor, regulation, signage, convention economics, and the reinvention of older properties." },
  { place: "Macau", country: "China", period: "Long gaming history · liberalized concessions in 2001", text: "Macau’s casino economy sits within a much older Chinese-Portuguese urban landscape. The development of Cotai on reclaimed land produced a different resort geography from the historic peninsula and increased debate about diversification beyond gaming revenue.", lens: "Separate historic streets and UNESCO-listed heritage from concession policy, Cotai infrastructure, mainland visitation, and non-gaming development." },
  { place: "Monte Carlo", country: "Monaco", period: "Casino enterprise founded in the 1860s", text: "Monte Carlo linked gaming with a purpose-built destination of gardens, theatre, hotels, rail access, and Belle Époque architecture. The casino became part of Monaco’s economic and cultural identity rather than an isolated gaming room.", lens: "Study Charles Garnier’s architecture, the Société des Bains de Mer, transport, performance culture, and Monaco’s restrictions on resident participation." },
  { place: "Singapore", country: "Singapore", period: "Integrated-resort policy approved in 2005", text: "Singapore used tightly regulated integrated resorts as a tourism and urban-development instrument. Marina Bay Sands became a major skyline structure, while social safeguards include entry levies and exclusion mechanisms for citizens and permanent residents.", lens: "Connect architecture and tourism policy with the Gambling Regulatory Authority, local safeguards, public transport, conventions, and the wider city." },
  { place: "Atlantic City", country: "United States", period: "Boardwalk opened in 1870 · casinos approved in 1976", text: "Atlantic City was a rail-access beach resort long before casino legalization. New Jersey introduced casinos as an economic-development strategy, but the city’s history also shows why a gaming industry cannot be treated as a complete urban policy.", lens: "Read the Boardwalk, housing, employment, regional competition, regulation, online gaming, and long-running redevelopment debates together." },
];

export default function Destinations() {
  return <>
    <Seo title="Casino destinations" description="Research Las Vegas, Macau, Monte Carlo, Singapore, and Atlantic City through history, architecture, culture, infrastructure, and regulation—not promotional rankings." path="/destinations" image={EXPANDED_IMAGES.destinations} />
    <article>
      <header className="casino-editorial-hero relative min-h-[70vh] overflow-hidden border-b border-gold/15"><img src={EXPANDED_IMAGES.destinations} alt="Casino destination study with world map, integrated-resort models, roulette-wheel compass, architectural photographs, and skyline" className="absolute inset-0 h-full w-full object-cover" /><div className="hero-vignette absolute inset-0" /><div className="container relative flex min-h-[70vh] items-end pb-16 pt-28"><div className="max-w-4xl"><p className="eyebrow">Atlas of place and policy</p><h1 className="mt-5 font-display text-6xl leading-[.92] text-ivory sm:text-7xl lg:text-9xl">Five destinations, five different systems.</h1><p className="mt-6 max-w-3xl text-xl leading-9 text-ivory/72">Casino cities are shaped by transport, land, architecture, labor, public authority, entertainment, and local culture. This is context—not a travel ranking.</p><p className="mt-6 text-sm text-ivory/45">CasinooVerse Destinations Desk · Reviewed 3 September 2026 · Editorial illustration</p></div></div></header>

      <section className="section-pad"><div className="container grid gap-12 lg:grid-cols-[1fr_360px]"><div className="article-body max-w-3xl"><p>Calling a place a casino destination can hide more than it reveals. Las Vegas expanded through highway and air travel; Macau’s resort geography depends on concession policy and reclaimed land; Monte Carlo grew from a sovereign development strategy; Singapore imposed an integrated-resort model with explicit social controls; Atlantic City layered casinos onto an older boardwalk economy.</p><p>The profiles below ask the same questions of each place: What existed before the casino economy? Who regulates it? How did architecture and transport change? What non-gaming culture matters? Which social risks are visible?</p></div><aside className="research-method-card self-start"><MapPinned className="h-5 w-5 text-gold" /><h2 className="mt-4 font-display text-3xl text-ivory">No “best casino” list</h2><p className="mt-4 text-sm leading-7 text-ivory/58">CasinooVerse does not rank destinations or recommend venues. These profiles explain urban and regulatory context and link to public sources.</p></aside></div></section>

      <section className="section-pad border-y border-white/8 bg-white/[.02]"><div className="container"><SectionHeading eyebrow="Destination dossiers" title="Place before spectacle" description="Each dossier begins with the city and its institutions—not the casino floor." /><div className="mt-12 space-y-7">{destinations.map((item, index) => <section key={item.place} className="editorial-card grid overflow-hidden lg:grid-cols-[210px_1fr_1fr]"><div className="border-b border-white/10 p-7 lg:border-b-0 lg:border-r"><p className="eyebrow">{String(index + 1).padStart(2, "0")} · {item.country}</p><h2 className="mt-4 font-display text-4xl text-ivory">{item.place}</h2><p className="mt-4 text-xs uppercase tracking-[.18em] text-ivory/38">{item.period}</p></div><div className="border-b border-white/10 p-7 lg:border-b-0 lg:border-r"><h3 className="text-sm font-semibold uppercase tracking-[.18em] text-gold-light">Context</h3><p className="mt-4 leading-8 text-ivory/62">{item.text}</p></div><div className="p-7"><h3 className="text-sm font-semibold uppercase tracking-[.18em] text-gold-light">Research lens</h3><p className="mt-4 leading-8 text-ivory/62">{item.lens}</p></div></section>)}</div></div></section>

      <section className="section-pad"><div className="container"><SectionHeading eyebrow="Comparative reading" title="Three questions travel writing should not skip" /><div className="mt-10 grid gap-6 md:grid-cols-3"><div className="border-t border-gold/30 pt-6"><TrainFront className="h-6 w-6 text-gold" /><h2 className="mt-4 font-display text-3xl text-ivory">How do people arrive?</h2><p className="mt-3 leading-7 text-ivory/58">Rail, airports, ferries, highways, border rules, and public transport determine who can visit and which districts receive investment.</p></div><div className="border-t border-gold/30 pt-6"><Building2 className="h-6 w-6 text-gold" /><h2 className="mt-4 font-display text-3xl text-ivory">What else is built?</h2><p className="mt-3 leading-7 text-ivory/58">Housing, theatres, convention halls, parks, retail, restaurants, utilities, and public space reveal the broader development model.</p></div><div className="border-t border-gold/30 pt-6"><Scale className="h-6 w-6 text-gold" /><h2 className="mt-4 font-display text-3xl text-ivory">Who sets the limits?</h2><p className="mt-3 leading-7 text-ivory/58">Licensing, tax, entry controls, exclusion tools, anti-money-laundering rules, and public-health policy vary sharply by jurisdiction.</p></div></div></div></section>

      <section className="section-pad border-y border-white/8 bg-black/20"><div className="container flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">Related reporting</p><h2 className="mt-3 max-w-3xl font-display text-5xl text-ivory">Follow culture and current development separately.</h2><p className="mt-5 max-w-2xl leading-8 text-ivory/60">The culture desk studies how places are represented. The daily archive tracks policy, operators, tourism, and market change with dated sources.</p></div><div className="flex flex-wrap gap-3"><Link href="/culture" className="button-ghost">Casino culture <ArrowRight className="h-4 w-4" /></Link><Link href="/category/culture-travel" className="button-gold">Current travel reporting</Link></div></div></section>

      <ResearchReferences title="Destination research references" intro="These sources support the urban, architectural, historical, and institutional context. Official visitor organizations are used for infrastructure context, not promotional claims." sources={[
        { name: "Rutgers — Eagleton Center", detail: "Atlantic City and casino-gambling history.", href: "https://governors.rutgers.edu/atlantic-city-and-casino-gambling-history/" },
        { name: "Safdie Architects", detail: "Architectural record for the Marina Bay Sands integrated-resort project.", href: "https://www.safdiearchitects.com/projects/marina-bay-sands-integrated-resort" },
        { name: "Monte-Carlo SBM", detail: "Institutional history of the company and destination development.", href: "https://www.montecarlosbm-corporate.com/the-company/history/" },
        { name: "UNLV Gaming Research & Review Journal", detail: "Research on Macau gaming inspectors and regulation.", href: "https://oasis.library.unlv.edu/grrj/vol26/iss1/4/" },
        { name: "Nevada Gaming Control Board", detail: "Official regulatory and statistical publications for Nevada.", href: "https://www.gaming.nv.gov/about-us/statistics-and-publications/" },
      ]} />
    </article>
  </>;
}
