import { useMemo, useState } from "react";
import { AlertTriangle, BarChart3, Clock3, Landmark, Sigma } from "lucide-react";
import { Seo } from "@/components/Seo";
import { ResearchReferences } from "@/components/ResearchReferences";
import { SectionHeading } from "@/components/SectionHeading";
import { EXPANDED_IMAGES } from "@/lib/expandedContent";

const facts = [
  { category: "History", title: "Venice authorized the Ridotto in 1638", text: "It provided controlled gaming during carnival and is widely described as an early public, government-sanctioned gaming house. Gambling itself is far older than the building.", source: "Georgia State University" },
  { category: "Games", title: "A single-zero roulette wheel has 37 pockets", text: "Numbers 1–36 plus zero produce a standard house edge of about 2.70% on ordinary bets. A double-zero wheel has 38 pockets and about a 5.26% edge.", source: "PBS Frontline; First Nations Development Institute" },
  { category: "Games", title: "Sixteen cards in a standard deck count as ten in blackjack", text: "The four tens, four jacks, four queens, and four kings make ten-value cards a little over 30% of a 52-card deck before any cards are dealt.", source: "Encyclopaedia Britannica; standard deck arithmetic" },
  { category: "Technology", title: "Modern slot outcomes are selected before the animation finishes", text: "A random-number generator selects a result at activation; reel motion and sound present that result. Earlier outcomes do not make a later outcome due.", source: "USC Viterbi School of Engineering" },
  { category: "Law", title: "The Indian Gaming Regulatory Act became law in 1988", text: "IGRA created a federal framework for gaming on Indian lands and established the National Indian Gaming Commission. Tribal and commercial gaming are distinct legal and economic systems.", source: "U.S. Census Bureau; NIGC" },
  { category: "Markets", title: "Market statistics describe a period, not a permanent rank", text: "Gross gaming revenue changes with regulation, travel, currency, openings, closures, and reporting definitions. CasinoVerse always keeps the date and jurisdiction attached to a figure.", source: "UK Gambling Commission; Nevada Gaming Control Board" },
  { category: "Culture", title: "Casino complexes have competed through architecture as well as games", text: "Research on Las Vegas describes eras of pool, sign, entrance, tower, and themed-resort competition. These features shaped the city’s visual identity and transport experience.", source: "UNLV Center for Gaming Research" },
  { category: "Risk", title: "A long-run percentage is not a session forecast", text: "House edge and theoretical return summarize many repeated events under fixed rules. Individual sessions may vary widely, and neither figure protects a person from loss.", source: "PBS Frontline; public-health guidance" },
];

export default function Facts() {
  const [filter, setFilter] = useState("All");
  const categories = ["All", ...Array.from(new Set(facts.map(fact => fact.category)))];
  const visible = useMemo(() => filter === "All" ? facts : facts.filter(fact => fact.category === filter), [filter]);

  return <>
    <Seo title="Casino facts" description="Verify casino history, game mathematics, regulation, markets, technology, architecture, and risk with dated sources and interpretation cautions." path="/facts" image={EXPANDED_IMAGES.facts} />
    <article>
      <header className="casino-editorial-hero relative min-h-[66vh] overflow-hidden border-b border-gold/15"><img src={EXPANDED_IMAGES.facts} alt="Casino mathematics bench with roulette wheel, cards, dice, slot reel, calipers, graph paper, and evidence tags" className="absolute inset-0 h-full w-full object-cover" /><div className="hero-vignette absolute inset-0" /><div className="container relative flex min-h-[66vh] items-end pb-16 pt-28"><div className="max-w-4xl"><p className="eyebrow">Facts with dates attached</p><h1 className="mt-5 font-display text-6xl leading-[.92] text-ivory sm:text-7xl lg:text-9xl">Interesting does not mean context-free.</h1><p className="mt-6 max-w-3xl text-xl leading-9 text-ivory/72">Eight concise facts about history, games, law, markets, technology, design, and risk—each paired with the condition that makes it meaningful.</p><p className="mt-6 text-sm text-ivory/45">CasinoVerse Research Desk · Reviewed 3 September 2026 · Editorial illustration</p></div></div></header>

      <section className="section-pad"><div className="container"><div className="grid gap-12 lg:grid-cols-[1fr_360px]"><div className="article-body max-w-3xl"><p>A fact can be technically correct and still mislead when its date, jurisdiction, denominator, or rule set is missing. CasinoVerse’s fact desk treats context as part of the fact.</p><p>Use the filters to browse subjects. Source institutions are listed below; rapidly changing market figures should always be checked against the newest release.</p></div><aside className="research-method-card self-start"><AlertTriangle className="h-5 w-5 text-gold" /><h2 className="mt-4 font-display text-3xl text-ivory">No record-chasing</h2><p className="mt-4 text-sm leading-7 text-ivory/58">This page does not promote the largest win, biggest jackpot, or highest spender. It explains systems, history, and measurement.</p></aside></div></div></section>

      <section className="section-pad border-y border-white/8 bg-white/[.02]"><div className="container"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><SectionHeading eyebrow="Evidence cards" title="Browse by subject" description="A selected filter changes the visible article cards but does not change their wording or sources." /><div className="flex max-w-full gap-2 overflow-x-auto pb-2" aria-label="Filter facts by subject">{categories.map(category => <button key={category} type="button" onClick={() => setFilter(category)} className={`filter-chip ${filter === category ? "is-active" : ""}`}>{category}</button>)}</div></div><div className="mt-12 grid gap-6 md:grid-cols-2">{visible.map((fact, index) => <section key={fact.title} className="editorial-card p-8"><div className="flex items-center justify-between gap-4"><span className="eyebrow">{fact.category}</span><span className="font-display text-3xl text-gold/45">{String(index + 1).padStart(2, "0")}</span></div><h2 className="mt-6 font-display text-4xl leading-tight text-ivory">{fact.title}</h2><p className="mt-5 leading-8 text-ivory/62">{fact.text}</p><p className="mt-6 border-t border-white/10 pt-5 text-xs uppercase tracking-[.15em] text-ivory/38">Reference: {fact.source}</p></section>)}</div></div></section>

      <section className="section-pad"><div className="container"><SectionHeading eyebrow="Three reading rules" title="What makes a number trustworthy" /><div className="mt-10 grid gap-6 md:grid-cols-3"><div className="border-t border-gold/30 pt-6"><Clock3 className="h-6 w-6 text-gold" /><h2 className="mt-4 font-display text-3xl text-ivory">Keep the date</h2><p className="mt-3 leading-7 text-ivory/58">Revenue, participation, and property counts change. A year is part of the claim.</p></div><div className="border-t border-gold/30 pt-6"><Landmark className="h-6 w-6 text-gold" /><h2 className="mt-4 font-display text-3xl text-ivory">Keep the jurisdiction</h2><p className="mt-3 leading-7 text-ivory/58">Commercial, tribal, online, lottery, and land-based categories use different legal definitions.</p></div><div className="border-t border-gold/30 pt-6"><Sigma className="h-6 w-6 text-gold" /><h2 className="mt-4 font-display text-3xl text-ivory">Keep the denominator</h2><p className="mt-3 leading-7 text-ivory/58">Probabilities and percentages are meaningful only when the rule set and comparison base are known.</p></div></div></div></section>

      <ResearchReferences title="Fact-desk references" intro="These institutions support the historical, mathematical, regulatory, and market context used on this page." sources={[
        { name: "Georgia State University", detail: "Research overview of casinos as historical and economic institutions.", href: "https://news.gsu.edu/2024/01/30/new-research-shows-how-casinos-changed-our-world-and-how-we-think/" },
        { name: "U.S. Census Bureau", detail: "Research on tribal gaming and economic conditions.", href: "https://www.census.gov/library/stories/2025/11/tribal-casinos.html" },
        { name: "UK Gambling Commission", detail: "Official industry statistics with defined periods and categories.", href: "https://www.gamblingcommission.gov.uk/statistics-and-research/publication/industry-statistics-november-2024-official-statistics" },
        { name: "Nevada Gaming Control Board", detail: "Official Nevada statistics and regulatory publications.", href: "https://www.gaming.nv.gov/about-us/statistics-and-publications/" },
        { name: "USC Viterbi School of Engineering", detail: "Technical overview of slot-machine outcome generation.", href: "https://illumin.usc.edu/inside-a-slot-machine/" },
        { name: "UNLV Center for Gaming Research", detail: "Research on architectural competition and casino development.", href: "https://oasis.library.unlv.edu/occ_papers/24/" },
      ]} />
    </article>
  </>;
}
