import { AlarmClock, Ban, HandHeart, MapPin, Phone, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { Seo } from "@/components/Seo";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";

export default function Support() {
  const { data = [], isLoading } = trpc.editorial.support.useQuery();
  return (
    <>
      <Seo title="Gambling-harm support directory" description="CasinoVerse internal directory of emergency guidance, helplines, counselling, self-exclusion, and financial-blocking information." path="/support" />
      <header className="support-directory-hero border-b border-[#7893A6]/25"><div className="container grid gap-10 py-16 md:py-24 lg:grid-cols-[1fr_360px] lg:items-end"><div><div className="flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-[#a9c2d0]" /><p className="eyebrow text-[#a9c2d0]">CasinoVerse support directory</p></div><h1 className="mt-6 max-w-5xl font-display text-[clamp(4rem,9vw,8rem)] leading-[.84] tracking-[-.045em] text-ivory">Create distance.<br /><em className="font-normal text-[#b4c7d4]">Ask for help.</em></h1><p className="mt-7 max-w-3xl text-xl leading-8 text-ivory/62">This CasinoVerse page stores responsible-play contacts and practical next steps in our own database. It does not redirect to another website.</p></div><aside className="rounded-[22px] border border-[#7893A6]/25 bg-[#11171a] p-6"><Ban className="h-6 w-6 text-[#a9c2d0]" /><h2 className="mt-4 font-display text-3xl text-ivory">Immediate danger</h2><p className="mt-4 text-sm leading-7 text-ivory/58">If someone is in immediate danger, severely distressed, or at risk of self-harm, contact the emergency service for the current location now. Do not wait for an online directory.</p></aside></div></header>
      <main className="section-space"><div className="container"><div className="max-w-3xl"><p className="eyebrow text-[#a9c2d0]">Stored support records</p><h2 className="mt-3 font-display text-5xl text-ivory">Practical routes to support</h2><p className="mt-5 text-lg leading-8 text-ivory/58">Availability changes by jurisdiction. Confirm phone numbers and service scope before relying on them, and use local emergency care for urgent situations.</p></div>{isLoading ? <div className="mt-12 grid gap-5 md:grid-cols-2">{Array.from({ length: 4 }, (_, index) => <Skeleton key={index} className="h-72 rounded-[22px] bg-white/5" />)}</div> : <div className="mt-12 grid gap-5 md:grid-cols-2">{data.map(resource => <section id={resource.slug} key={resource.id} className="support-directory-card scroll-mt-28"><div className="flex items-center justify-between gap-4"><span className="eyebrow text-[#a9c2d0]">{resource.serviceType.replaceAll("_", " ")}</span>{resource.serviceType === "helpline" ? <Phone className="h-5 w-5 text-[#a9c2d0]" /> : resource.serviceType === "emergency" ? <AlarmClock className="h-5 w-5 text-[#a9c2d0]" /> : <HandHeart className="h-5 w-5 text-[#a9c2d0]" />}</div><h2 className="mt-7 font-display text-3xl text-ivory">{resource.name}</h2><p className="mt-2 flex items-center gap-2 text-xs uppercase tracking-[.12em] text-ivory/38"><MapPin className="h-3.5 w-3.5" />{resource.jurisdiction}</p><p className="mt-5 leading-7 text-ivory/58">{resource.summary}</p>{resource.phone && <div className="mt-6 rounded-xl border border-[#7893A6]/20 bg-black/20 p-4"><p className="eyebrow text-ivory/35">Phone</p><p className="mt-2 font-display text-2xl text-ivory">{resource.phone}</p></div>}<p className="mt-6 border-t border-white/10 pt-5 text-sm leading-7 text-ivory/54">{resource.contactInstructions}</p></section>)}</div>}<div className="mt-14 rounded-[24px] border border-gold/15 bg-[#171410] p-8"><p className="eyebrow text-gold">Information boundary</p><p className="mt-4 max-w-5xl leading-8 text-ivory/58">CasinoVerse does not provide medical, psychological, legal, or financial advice and does not operate the listed services. This directory is stored for informational convenience and must not replace local professional assessment.</p><Link href="/responsible-entertainment" className="mt-6 inline-flex text-sm text-gold-light">Return to the responsible-play guide →</Link></div></div></main>
    </>
  );
}
