export const KNOWN_TYPOGRAPHY_IMAGE_URLS = new Set([
  "/manus-storage/cv-casino-editorial-home-master_dd528b70.jpg",
  "/manus-storage/cv-casino-editorial-floor-report_efb69f8c.jpg",
  "/manus-storage/cv-casino-editorial-industry_37397fe6.jpg",
  "/manus-storage/cv-casino-editorial-archive_118ba0e9.jpg",
  "/manus-storage/casinooverse-malaysia-gaming-child-safety-2026-09-11_2eb3bdd8.jpg",
  "/manus-storage/casinooverse-macau-tourism-tax-2026-09-11_bfd4d5db.jpg",
  "/manus-storage/pennsylvania-charitable-gaming-policy-editorial_119ef299.png",
  "/manus-storage/cv-redesign-story-virginia-v3_a162da61.jpg",
  "/manus-storage/cv-casino-editorial-blog-v2_e8bdb7f7.jpg",
  "/manus-storage/casinooverse-new-zealand-community-funds-2026-09-11_b172bfc3.jpg",
  "/manus-storage/casinooverse-fatf-gambling-risk-indicators-2026-09-11_e56c4039.jpg",
  "/manus-storage/cv-redesign-story-macau-promo-v3_378a5e1c.jpg",
  "/manus-storage/cv-redesign-story-newport-v3_6c4544d7.jpg",
  "/manus-storage/cv-redesign-story-uae-v3_7842f0be.jpg",
  "/manus-storage/cv-redesign-story-kangwon-v3_bf87c0c6.jpg",
  "/manus-storage/cv-redesign-story-gkl-v4_fc1a8e20.jpg",
  "/manus-storage/cv-redesign-story-hokkaido-v4_4377d0e6.jpg",
  "/manus-storage/cv-casino-story-philippines-visa_00e3c52c.jpg",
  "/manus-storage/cv-casino-story-rgb-machines_4f50affa.jpg",
  "/manus-storage/cv-casino-story-court-authority_1cbfe059.jpg",
  "/manus-storage/cv-casino-story-paradise-revenue_5da7f8d5.jpg",
  "/manus-storage/cv-casino-story-roulette-guide_416909f1.jpg",
  "/manus-storage/casinoverse-daily-research-archive-unique_189cac85.jpg",
  "/manus-storage/cv-casino-editorial-games-v2_112c40b6.jpg",
  "/manus-storage/cv-casino-editorial-history_ccc4b2ef.jpg",
  "/manus-storage/cv-casino-editorial-culture_5603c3fa.jpg",
  "/manus-storage/cv-casino-editorial-gallery_1b96ffcc.jpg",
  "/manus-storage/cv-redesign-gallery-archive-v3_6f28d974.jpg",
  "/manus-storage/cv-casino-editorial-responsible-v2_56db7e17.jpg",
  "/manus-storage/cv-casino-editorial-about-v2_da3ac0f6.jpg",
  "/manus-storage/casinooverse-textfree-012_eb3e70bf.jpg",
  "/manus-storage/casinooverse-textfree-051_17996e96.jpg",
  "/manus-storage/casinooverse-textfree-051-v2_ce325409.jpg",
]);

export function isKnownTypographyImage(url: string | null | undefined) {
  return Boolean(url && KNOWN_TYPOGRAPHY_IMAGE_URLS.has(url));
}
